#
# OPENSTEP build configuration.
#
# This configuration targets the OpenStep frontend build.
#

override PKG_CONFIG := pkg-config
override CC := /usr/local/bin/gcc
override BUILD_CC := /usr/local/bin/gcc
override CCACHE :=
override CC_CAN_BUILD_AND_DEP := no
override CC_CANNOT_DEP := yes

CFLAGS += -DNeXT -Di386 -D__ARCHITECTURE__=\"i386\" -DNO_IPV6 -Iinclude/netsurf -I/NextDeveloper/Headers -I/NextDeveloper/Headers/bsd -include utils/openstep.h
CXXFLAGS += -DNeXT -Di386 -D__ARCHITECTURE__=\"i386\" -I/NextDeveloper/Headers -I/NextDeveloper/Headers/bsd
COMMON_WARNFLAGS += -Wno-unused

override NETSURF_USE_CURL := YES
override NETSURF_USE_OPENSSL := YES
override NETSURF_USE_GIF := YES
override NETSURF_USE_JPEG := YES
override NETSURF_USE_NSLOG := YES
override NETSURF_USE_UTF8PROC := YES

override NETSURF_USE_BMP := YES
override NETSURF_USE_JPEGXL := NO
override NETSURF_USE_PNG := YES
override NETSURF_USE_VIDEO := NO
override NETSURF_USE_WEBP := NO
override NETSURF_USE_HARU_PDF := NO
override NETSURF_USE_NSPSL := NO
override NETSURF_USE_NSSVG := YES
override NETSURF_USE_ROSPRITE := NO
override NETSURF_USE_RSVG := NO

override NETSURF_USE_DUKTAPE := YES

override NETSURF_USE_LIBICONV_PLUG := NO
override NETSURF_STRIP_BINARY := NO
