# ----------------------------------------------------------------------------
# OPENSTEP-specific options
# ----------------------------------------------------------------------------

# Font renderer used by the libnsfb framebuffer renderer.
# Supported values:
#   internal  built-in framebuffer bitmap font
#   freetype  scalable fonts through FreeType2
NETSURF_FB_FONTLIB := freetype

# Default framebuffer FreeType font files/search path.  Release bundles put
# these faces in Resources/Fonts; the source path keeps developer builds usable.
NETSURF_FB_FONTPATH := ./frontends/openstep/res/fonts
NETSURF_FB_FONT_SANS_SERIF := DejaVuSans.ttf
NETSURF_FB_FONT_SANS_SERIF_BOLD := DejaVuSans-Bold.ttf
NETSURF_FB_FONT_SANS_SERIF_ITALIC := DejaVuSans-Oblique.ttf
NETSURF_FB_FONT_SANS_SERIF_ITALIC_BOLD := DejaVuSans-BoldOblique.ttf
NETSURF_FB_FONT_SERIF := DejaVuSerif.ttf
NETSURF_FB_FONT_SERIF_BOLD := DejaVuSerif-Bold.ttf
NETSURF_FB_FONT_SERIF_ITALIC := DejaVuSerif-Italic.ttf
NETSURF_FB_FONT_SERIF_ITALIC_BOLD := DejaVuSerif-BoldItalic.ttf
NETSURF_FB_FONT_MONOSPACE := DejaVuSansMono.ttf
NETSURF_FB_FONT_MONOSPACE_BOLD := DejaVuSansMono-Bold.ttf
NETSURF_FB_FONT_MONOSPACE_ITALIC := DejaVuSansMono-Oblique.ttf
NETSURF_FB_FONT_MONOSPACE_ITALIC_BOLD := DejaVuSansMono-BoldOblique.ttf
NETSURF_FB_FONT_CURSIVE := DejaVuSans-Oblique.ttf
NETSURF_FB_FONT_FANTASY := DejaVuSans-Bold.ttf

# Where to search for NetSurf's resources after looking in ~/.netsurf and
# $NETSURFRES.  It must have a trailing /
NETSURF_OPENSTEP_RES_PATH := $(PREFIX)/share/netsurf/:./frontends/openstep/res/

# Disable javascript for the moment
NETSURF_USE_DUKTAPE := NO

# Enable NetSurf's use of librsvg in conjunction with Cairo to display SVGs
# Valid options: YES, NO, AUTO
NETSURF_USE_RSVG := AUTO

# Enable NetSurf's use of libsvgtiny for displaying SVGs
# Valid options: YES, NO, AUTO
NETSURF_USE_NSSVG := AUTO

# Enable NetSurf's use of librosprite for displaying RISC OS Sprites
# Valid options: YES, NO, AUTO
NETSURF_USE_ROSPRITE := AUTO
