# utils sources

S_UTILS := \
	bloom.c \
	corestrings.c \
	file.c \
	filepath.c \
	hashmap.c \
	hashtable.c \
	idna.c \
	libdom.c \
	log.c \
	messages.c \
	nscolour.c \
	nsoption.c \
	punycode.c \
	ssl_certs.c \
	talloc.c \
	time.c \
	url.c \
	useragent.c \
	utf8.c \
	utils.c

ifeq ($(HOST),NeXT)
S_UTILS += openstep_compat.c
endif

S_UTILS := $(addprefix utils/,$(S_UTILS))
